pipeline:
    name: ALM Pipeline
    identifier: ALM_Pipeline
    projectIdentifier: Project_123
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: Git_connector
                build: <+input>
    stages:
        - stage:
              name: Development
              identifier: Development
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: VM
                      spec:
                          type: Pool
                          spec:
                              identifier: " us-east-1_6cJvK46mF"
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Dev Run
                                identifier: Dev_Run
                                spec:
                                    shell: Sh
                                    command: cd
        - stage:
              name: Approval
              identifier: Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approvers
                                identifier: Approvers
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.Approvers
                                    approverInputs: []
              tags: {}
        - stage:
              name: Production
              identifier: Production
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      useFromStage: Development
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Another Run
                                identifier: Another_Run
                                spec:
                                    shell: Sh
                                    command: cd
    delegateSelectors:
        - dockerdelegate
